version: "3"
services:
  flask_web:
    build: ./flask_web
    ports:
      - "5051:5000"
    container_name: flask_web_pro
    command: python3 manage.py runserver
    networks:
      - flask_web_net
networks:
  flask_web_net:
    driver: bridge